// ═══════════════════════════════════════════════════════════
// TMDB-shaped metadata layer
// Fields mirror TMDB's /movie/{id} and /tv/{id} responses so a
// live fetch could drop in later. Hydrated at build time here.
// ═══════════════════════════════════════════════════════════

// Gradient keys per genre — used as the cinematic backdrop
// when we don't have a real TMDB backdrop_path. Two-color
// hero gradients tuned to genre mood.
const GENRE_BACKDROPS = {
  'Sports':       { c1: '#0a1f3d', c2: '#c8352d', accent: '#ffb800', mood: 'stadium-night' },
  'Drama':        { c1: '#1a0d2e', c2: '#3f1d5c', accent: '#a78bfa', mood: 'noir-interior' },
  'Thriller':     { c1: '#0b0b14', c2: '#2c0a1f', accent: '#ff4d6a', mood: 'cold-dark'    },
  'Documentary':  { c1: '#062a2a', c2: '#0d5c5c', accent: '#39d98a', mood: 'archive'      },
  'Lifestyle':    { c1: '#3a1f0a', c2: '#8a4a1a', accent: '#f0c040', mood: 'kitchen-warm' },
  'Reality':      { c1: '#3d0a3d', c2: '#8a1a66', accent: '#ff4d6a', mood: 'confessional' },
  'Scripted':     { c1: '#0a1a3d', c2: '#1a4a8a', accent: '#36c5f0', mood: 'cinematic'    },
  'Comedy':       { c1: '#3d2a0a', c2: '#c78a1a', accent: '#f0c040', mood: 'daylight'     },
  'Branded':      { c1: '#0a2a1f', c2: '#1a6b4a', accent: '#39d98a', mood: 'product-clean'},
  'Animation':    { c1: '#2e0a3d', c2: '#8a1aa0', accent: '#a78bfa', mood: 'vivid'        },
};

// Per-program TMDB-shaped records. Keyed by program rank (1..12) so
// Content, CPG, and Exchange can all reference them by id.
// Fields map 1:1 to TMDB responses; the artifact ships offline.
const TMDB_RECORDS = {
  1: {
    tmdb_id: 811001, media_type: 'tv',
    title: 'SUNDAY NIGHT COUNTDOWN', original_title: 'Sunday Night Countdown',
    tagline: 'Every kickoff. Every story. Every Sunday.',
    overview: "ESPN's flagship pre-game show delivers live analysis, expert breakdowns, and on-location reports from every NFL Sunday matchup. Anchored by a rotating cast of former players and analysts.",
    release_date: '2013-09-08', first_air_date: '2013-09-08',
    runtime: 120, status: 'Returning Series',
    genres: ['Sports', 'Pre-Game', 'Live'],
    keywords: ['nfl', 'football', 'live', 'pre-game', 'analysis', 'espn', 'sunday', 'sports-talk', 'on-location'],
    vote_average: 8.4, vote_count: 24180, popularity: 284.7,
    production_companies: [{ name: 'ESPN Films', logo_path: null }, { name: 'ESPN Sports', logo_path: null }],
    networks: [{ name: 'ESPN', logo_path: null }],
    created_by: [{ name: 'Stuart Scott', job: 'Original Creator' }],
    credits: {
      cast: [
        { name: 'Scott Van Pelt', character: 'Host',      order: 0 },
        { name: 'Suzy Kolber',    character: 'Anchor',    order: 1 },
        { name: 'Booger McFarland',character: 'Analyst',  order: 2 },
        { name: 'Adam Schefter',  character: 'Insider',   order: 3 },
      ],
      crew: [
        { name: 'Seth Markman',  job: 'Executive Producer' },
        { name: 'Lee Fitting',   job: 'SVP Production' },
      ]
    },
    // Financials (TMDB only gives this for movies; we extend for TV with deal data)
    budget: 58_000_000, revenue: 142_000_000,
    deal_value: 8_400_000, rights_cost: 1_700_000,
    // Awards
    awards: [
      { label: 'SPORTS EMMY', year: 2024, result: 'Winner',  category: 'Outstanding Studio Show' },
      { label: 'SPORTS EMMY', year: 2023, result: 'Nominee', category: 'Outstanding Live Series' },
      { label: 'CSA AWARDS',  year: 2022, result: 'Winner',  category: 'Best On-Air Talent'      },
    ],
    // Streaming windows
    watch_providers: {
      US: {
        flatrate: ['ESPN+', 'Hulu', 'YouTube TV', 'Fubo'],
        rent: [], buy: [],
        free: ['ESPN.com']
      }
    },
    // Performance
    ratings_trend: [2.41, 2.52, 2.48, 2.61, 2.73, 2.68, 2.84, 2.91],
    social_velocity: 164,
    certification: 'TV-PG',
  },
  2: {
    tmdb_id: 811002, media_type: 'tv',
    title: 'THE LAST CONVOY', original_title: 'The Last Convoy',
    tagline: 'The road ends. The war begins.',
    overview: "A military supply convoy becomes the last hope for a besieged American outpost when all other routes are cut off. From the producers of Jack Ryan.",
    release_date: '2024-02-11', first_air_date: '2024-02-11',
    runtime: 52, status: 'Returning Series',
    genres: ['Drama', 'Action', 'War'],
    keywords: ['military', 'convoy', 'thriller', 'war', 'supply-line', 'outpost', 'conspiracy', 'besieged'],
    vote_average: 7.8, vote_count: 8420, popularity: 198.3,
    production_companies: [{ name: 'Oakhurst Studios', logo_path: null }, { name: 'Skydance TV', logo_path: null }],
    networks: [{ name: 'USA Network', logo_path: null }],
    created_by: [{ name: 'Michael Bay', job: 'Executive Producer' }],
    credits: {
      cast: [
        { name: 'Jake Gyllenhaal',     character: 'Sgt. Marcus Reid',  order: 0 },
        { name: 'Oscar Isaac',         character: 'Lt. Dean Walsh',    order: 1 },
        { name: 'Tessa Thompson',      character: 'Capt. Maya Chen',   order: 2 },
        { name: 'Giancarlo Esposito',  character: 'Col. Harlan Vaughn', order: 3 },
      ],
      crew: [
        { name: 'Michael Bay',     job: 'Executive Producer' },
        { name: 'Taylor Sheridan', job: 'Co-Executive Producer' },
      ]
    },
    budget: 88_000_000, revenue: 212_400_000,
    deal_value: 4_800_000, rights_cost: 4_200_000,
    awards: [
      { label: 'CRITICS CHOICE', year: 2024, result: 'Winner',  category: 'Best Action Series' },
      { label: 'SAG AWARDS',     year: 2024, result: 'Nominee', category: 'Ensemble in Drama'  },
    ],
    watch_providers: {
      US: {
        flatrate: ['USA', 'Peacock', 'Hulu'],
        rent: ['Prime Video', 'Apple TV', 'YouTube'],
        buy: ['Apple TV', 'Prime Video'],
      }
    },
    ratings_trend: [1.62, 1.71, 1.74, 1.81, 1.88, 1.86, 1.92, 1.97],
    social_velocity: 142,
    certification: 'TV-MA',
  },
  3: {
    tmdb_id: 811003, media_type: 'tv',
    title: 'MIDNIGHT KITCHEN', original_title: 'Midnight Kitchen',
    tagline: 'After hours. Off-menu. Unfiltered.',
    overview: "Celebrity chefs take over closed restaurants after midnight to cook for kitchen staff, sanitation workers, and late-shift EMTs. No cameras in the dining room — just the line.",
    release_date: '2019-04-22', first_air_date: '2019-04-22',
    runtime: 44, status: 'Returning Series',
    genres: ['Lifestyle', 'Food', 'Documentary'],
    keywords: ['chef', 'kitchen', 'food', 'late-night', 'hospitality', 'restaurant', 'community', 'intimate'],
    vote_average: 8.1, vote_count: 3140, popularity: 112.4,
    production_companies: [{ name: 'Zero Point Zero', logo_path: null }, { name: 'Food Network Originals', logo_path: null }],
    networks: [{ name: 'Food Network', logo_path: null }],
    created_by: [{ name: 'David Chang', job: 'Executive Producer' }],
    credits: {
      cast: [
        { name: 'David Chang',      character: 'Host',        order: 0 },
        { name: 'Roy Choi',         character: 'Featured',    order: 1 },
        { name: 'Samin Nosrat',     character: 'Featured',    order: 2 },
      ],
      crew: [ { name: 'Christopher Collins', job: 'Showrunner' } ]
    },
    budget: 12_400_000, revenue: 38_200_000,
    deal_value: 2_100_000, rights_cost: 850_000,
    awards: [ { label: 'JAMES BEARD', year: 2023, result: 'Winner', category: 'Outstanding Food TV' } ],
    watch_providers: { US: { flatrate: ['Max', 'Discovery+', 'Hulu'], rent: [], buy: [] } },
    ratings_trend: [1.18, 1.24, 1.31, 1.28, 1.34, 1.39, 1.41, 1.38],
    social_velocity: 98,
    certification: 'TV-14',
  },
  4: {
    tmdb_id: 811004, media_type: 'tv',
    title: 'HAMMER & NAIL', original_title: 'Hammer & Nail',
    tagline: 'A house is just the first draft.',
    overview: "Two siblings — one a structural engineer, one a conceptual artist — renovate generational homes in small American towns. Competing visions, one family at the center.",
    release_date: '2020-09-15',
    runtime: 44, status: 'Returning Series',
    genres: ['Lifestyle', 'Home', 'Reality'],
    keywords: ['renovation', 'family', 'home', 'design', 'hgtv', 'small-town', 'siblings'],
    vote_average: 7.4, vote_count: 2100, popularity: 89.1,
    production_companies: [{ name: 'High Noon Entertainment', logo_path: null }],
    networks: [{ name: 'HGTV', logo_path: null }],
    created_by: [{ name: 'Patrick Kramp', job: 'Creator' }],
    credits: { cast: [
      { name: 'Jasmine Roth',  character: 'Host', order: 0 },
      { name: 'Ty Pennington', character: 'Host', order: 1 },
    ], crew: []},
    budget: 9_800_000, revenue: 24_100_000,
    deal_value: 1_400_000, rights_cost: 620_000,
    awards: [],
    watch_providers: { US: { flatrate: ['Max', 'Discovery+'], rent: [], buy: [] } },
    ratings_trend: [1.42, 1.39, 1.45, 1.41, 1.38, 1.36, 1.38, 1.34],
    social_velocity: 72,
    certification: 'TV-G',
  },
  5: {
    tmdb_id: 811005, media_type: 'tv',
    title: 'IRONFORGE', original_title: 'Ironforge',
    tagline: 'Steel remembers.',
    overview: "Deep-dive documentary series tracking the last independent steel mills in Appalachia. Each episode follows a single piece of forged steel from raw ore to installed infrastructure.",
    release_date: '2018-06-03',
    runtime: 52, status: 'Returning Series',
    genres: ['Documentary', 'Industrial', 'Historical'],
    keywords: ['steel', 'appalachia', 'industry', 'craftsmanship', 'american-manufacturing', 'long-form'],
    vote_average: 8.6, vote_count: 1820, popularity: 64.2,
    production_companies: [{ name: 'Meridian Media', logo_path: null }, { name: 'HISTORY Originals', logo_path: null }],
    networks: [{ name: 'HISTORY', logo_path: null }],
    created_by: [{ name: 'Lauren Greenfield', job: 'Director' }],
    credits: { cast: [{ name: 'Morgan Freeman', character: 'Narrator', order: 0 }], crew: [] },
    budget: 6_200_000, revenue: 14_800_000,
    deal_value: 2_100_000, rights_cost: 1_900_000,
    awards: [
      { label: 'PEABODY',  year: 2022, result: 'Winner',  category: 'Documentary' },
      { label: 'DUPONT',   year: 2021, result: 'Winner',  category: 'Long-Form Journalism' },
    ],
    watch_providers: { US: { flatrate: ['History Vault', 'Hulu'], rent: ['Prime Video', 'Apple TV'], buy: ['Apple TV', 'Prime Video'] } },
    ratings_trend: [1.04, 1.12, 1.18, 1.16, 1.22, 1.21, 1.22, 1.28],
    social_velocity: 58,
    certification: 'TV-PG',
  },
  6: {
    tmdb_id: 811006, media_type: 'tv',
    title: 'LONE STAR CROSSING', original_title: 'Lone Star Crossing',
    tagline: 'Blood runs deeper than the border.',
    overview: "A multigenerational saga following a Black Texas ranching family whose land sits on top of what might be the last undiscovered oil reserve in the Lower 48.",
    release_date: '2023-10-09', first_air_date: '2023-10-09',
    runtime: 48, status: 'Returning Series',
    genres: ['Scripted', 'Drama', 'Family Saga'],
    keywords: ['texas', 'family', 'oil', 'ranch', 'legacy', 'black-cinema', 'epic'],
    vote_average: 8.9, vote_count: 4280, popularity: 224.8,
    production_companies: [{ name: 'Tyler Perry Studios', logo_path: null }, { name: 'BET Originals', logo_path: null }],
    networks: [{ name: 'BET', logo_path: null }],
    created_by: [{ name: 'Regina King', job: 'Creator & Director' }],
    credits: {
      cast: [
        { name: 'Sterling K. Brown',   character: 'Elias Reed',   order: 0 },
        { name: 'Danai Gurira',        character: 'Mae Reed',     order: 1 },
        { name: 'Courtney B. Vance',   character: 'Silas Reed',   order: 2 },
        { name: 'Zendaya',             character: 'Young Ada',    order: 3 },
      ],
      crew: [ { name: 'Barry Jenkins', job: 'Executive Producer' } ]
    },
    budget: 68_000_000, revenue: 184_200_000,
    deal_value: 6_900_000, rights_cost: 3_400_000,
    awards: [
      { label: 'NAACP IMAGE', year: 2024, result: 'Winner',  category: 'Outstanding Drama Series' },
      { label: 'EMMY',        year: 2024, result: 'Nominee', category: 'Outstanding Drama' },
    ],
    watch_providers: { US: { flatrate: ['BET+', 'Paramount+', 'Hulu'], rent: ['Prime Video'], buy: ['Apple TV'] } },
    ratings_trend: [0.84, 0.92, 0.98, 1.02, 1.08, 1.11, 1.14, 1.22],
    social_velocity: 218,
    certification: 'TV-MA',
  },
  7: {
    tmdb_id: 811007, media_type: 'tv',
    title: 'CAPE LIGHT', original_title: 'Cape Light',
    tagline: 'The tide always brings something home.',
    overview: "A widowed lighthouse keeper on the Outer Banks takes in her estranged granddaughter for the summer, uncovering the family's long-buried ties to a shipwreck from 1962.",
    release_date: '2021-08-14',
    runtime: 48, status: 'Returning Series',
    genres: ['Drama', 'Family', 'Romance'],
    keywords: ['lighthouse', 'family', 'coastal', 'shipwreck', 'mystery', 'summer', 'hallmark'],
    vote_average: 7.2, vote_count: 980, popularity: 48.4,
    production_companies: [{ name: 'Crown Media Originals', logo_path: null }],
    networks: [{ name: 'Hallmark Channel', logo_path: null }],
    created_by: [{ name: 'Diana Gabaldon', job: 'Developed For TV' }],
    credits: { cast: [
      { name: 'Jessica Lange',    character: 'Eleanor', order: 0 },
      { name: 'Felicity Jones',   character: 'Nora',    order: 1 },
    ], crew: []},
    budget: 14_800_000, revenue: 32_400_000,
    deal_value: 1_800_000, rights_cost: 740_000,
    awards: [],
    watch_providers: { US: { flatrate: ['Hallmark Movies Now', 'Peacock'], rent: [], buy: [] } },
    ratings_trend: [1.02, 1.06, 1.04, 1.08, 1.11, 1.08, 1.08, 1.04],
    social_velocity: 42,
    certification: 'TV-PG',
  },
  8: {
    tmdb_id: 811008, media_type: 'tv',
    title: 'DEEP OCEAN ARCHIVES', original_title: 'Deep Ocean Archives',
    tagline: 'What the surface forgets, the abyss keeps.',
    overview: "4K submersible footage from unexplored trenches, paired with archival Cold War-era sonar maps. Hosted by Sylvia Earle.",
    release_date: '2016-03-22',
    runtime: 60, status: 'Returning Series',
    genres: ['Documentary', 'Science', 'Nature'],
    keywords: ['ocean', 'submersible', 'deep-sea', 'exploration', 'science', 'cold-war', '4k'],
    vote_average: 8.8, vote_count: 3840, popularity: 96.2,
    production_companies: [{ name: 'BBC Studios', logo_path: null }, { name: 'Discovery Originals', logo_path: null }],
    networks: [{ name: 'Discovery', logo_path: null }],
    created_by: [{ name: 'James Cameron', job: 'Executive Producer' }],
    credits: { cast: [{ name: 'Sylvia Earle', character: 'Host',  order: 0 }], crew: [] },
    budget: 22_400_000, revenue: 48_200_000,
    deal_value: 3_200_000, rights_cost: 1_400_000,
    awards: [
      { label: 'BAFTA TV',   year: 2022, result: 'Winner', category: 'Specialist Factual' },
      { label: 'EMMY',       year: 2021, result: 'Winner', category: 'Outstanding Nature Documentary' },
    ],
    watch_providers: { US: { flatrate: ['Discovery+', 'Max', 'PBS Passport'], rent: ['Prime Video'], buy: ['Apple TV'] } },
    ratings_trend: [1.12, 1.08, 1.04, 1.02, 0.98, 0.96, 0.98, 0.94],
    social_velocity: 64,
    certification: 'TV-G',
  },
  9: {
    tmdb_id: 811009, media_type: 'tv',
    title: 'PAPER CITIES', original_title: 'Paper Cities',
    tagline: 'The architect drew the blueprint. The city drew the line.',
    overview: "A starchitect returns to his hometown to design a billion-dollar megadevelopment — only to discover the land was fraudulently seized from his own grandparents in 1968.",
    release_date: '2024-01-28', first_air_date: '2024-01-28',
    runtime: 54, status: 'Returning Series',
    genres: ['Drama', 'Thriller', 'Legal'],
    keywords: ['architecture', 'real-estate', 'legacy', 'redlining', 'conspiracy', 'prestige-drama'],
    vote_average: 8.7, vote_count: 6420, popularity: 248.6,
    production_companies: [{ name: 'FX Productions', logo_path: null }, { name: 'MRC Television', logo_path: null }],
    networks: [{ name: 'FX', logo_path: null }],
    created_by: [{ name: 'Jesse Armstrong', job: 'Creator' }],
    credits: {
      cast: [
        { name: 'Mahershala Ali',  character: 'Julian Keene',   order: 0 },
        { name: 'Viola Davis',     character: 'Ruth Whitlock',  order: 1 },
        { name: 'Riz Ahmed',       character: 'Mikael Farsi',   order: 2 },
      ],
      crew: [{ name: 'Jonathan Glazer', job: 'Pilot Director' }]
    },
    budget: 112_000_000, revenue: 268_400_000,
    deal_value: 10_800_000, rights_cost: 8_900_000,
    awards: [
      { label: 'GOLDEN GLOBE', year: 2024, result: 'Winner',  category: 'Best Drama Series' },
      { label: 'EMMY',         year: 2024, result: 'Nominee', category: 'Outstanding Drama' },
      { label: 'PEABODY',      year: 2024, result: 'Winner',  category: 'Drama' },
    ],
    watch_providers: { US: { flatrate: ['Hulu', 'FX on Hulu'], rent: ['Apple TV', 'Prime Video'], buy: ['Apple TV'] } },
    ratings_trend: [0.72, 0.78, 0.82, 0.84, 0.86, 0.88, 0.94, 1.02],
    social_velocity: 284,
    certification: 'TV-MA',
  },
  10: {
    tmdb_id: 811010, media_type: 'tv',
    title: 'THE OVERNIGHT', original_title: 'The Overnight',
    tagline: 'The city sleeps. The ward doesn\'t.',
    overview: "Procedural drama set in the overnight shift of a Level 1 trauma center in Baltimore, following a rotating crew of residents, nurses, and the EMTs who bring the night in.",
    release_date: '2024-03-04',
    runtime: 42, status: 'Returning Series',
    genres: ['Thriller', 'Medical', 'Drama'],
    keywords: ['hospital', 'overnight', 'trauma', 'baltimore', 'medical', 'procedural'],
    vote_average: 7.6, vote_count: 2180, popularity: 128.4,
    production_companies: [{ name: 'John Wells Productions', logo_path: null }],
    networks: [{ name: 'TNT', logo_path: null }],
    created_by: [{ name: 'John Wells', job: 'Creator' }],
    credits: { cast: [
      { name: 'Wagner Moura',   character: 'Dr. Andre Silva', order: 0 },
      { name: 'Lupita Nyong\'o', character: 'Dr. Imani Okafor', order: 1 },
    ], crew: []},
    budget: 48_000_000, revenue: 98_200_000,
    deal_value: 3_400_000, rights_cost: 1_800_000,
    awards: [],
    watch_providers: { US: { flatrate: ['Max', 'TNT Drama'], rent: ['Apple TV'], buy: [] } },
    ratings_trend: [0.92, 0.94, 0.91, 0.89, 0.88, 0.89, 0.89, 0.91],
    social_velocity: 88,
    certification: 'TV-14',
  },
  11: {
    tmdb_id: 811011, media_type: 'tv',
    title: 'HIDDEN PROVINCE', original_title: 'Hidden Province',
    tagline: 'Somewhere you\'ve never been. Someone they used to be.',
    overview: "Reality series where affluent Manhattanites are dropped into villages in China's Guizhou province and matched with a host family for 60 days. No translator, no cameras past 8pm.",
    release_date: '2019-11-06',
    runtime: 44, status: 'Returning Series',
    genres: ['Reality', 'Travel', 'Cultural'],
    keywords: ['reality', 'china', 'cultural-exchange', 'bravo', 'documentary-reality', 'immersive'],
    vote_average: 7.9, vote_count: 1640, popularity: 78.2,
    production_companies: [{ name: 'Shed Media', logo_path: null }],
    networks: [{ name: 'Bravo', logo_path: null }],
    created_by: [{ name: 'Andy Cohen', job: 'Executive Producer' }],
    credits: { cast: [{ name: 'Andy Cohen', character: 'Host', order: 0 }], crew: [] },
    budget: 11_200_000, revenue: 26_400_000,
    deal_value: 1_200_000, rights_cost: 540_000,
    awards: [],
    watch_providers: { US: { flatrate: ['Peacock', 'Hayu'], rent: [], buy: [] } },
    ratings_trend: [0.64, 0.68, 0.72, 0.76, 0.78, 0.81, 0.84, 0.88],
    social_velocity: 124,
    certification: 'TV-14',
  },
  12: {
    tmdb_id: 811012, media_type: 'tv',
    title: 'COAST TO COAST: DINERS', original_title: 'Coast to Coast: Diners',
    tagline: 'America, one booth at a time.',
    overview: "Guy Fieri hops between 24-hour diners, roadside truck stops, and overnight breakfast counters from Portland to Portland. Each episode: 4 stops, 1 state, 1 story.",
    release_date: '2010-05-15',
    runtime: 30, status: 'Returning Series',
    genres: ['Lifestyle', 'Food', 'Travel'],
    keywords: ['diner', 'road-trip', 'food', 'americana', 'guy-fieri', 'long-running'],
    vote_average: 7.1, vote_count: 4820, popularity: 112.6,
    production_companies: [{ name: 'Citizen Pictures', logo_path: null }],
    networks: [{ name: 'Food Network', logo_path: null }],
    created_by: [{ name: 'Guy Fieri', job: 'Host & Producer' }],
    credits: { cast: [{ name: 'Guy Fieri', character: 'Host', order: 0 }], crew: [] },
    budget: 18_400_000, revenue: 56_200_000,
    deal_value: 2_400_000, rights_cost: 1_100_000,
    awards: [ { label: 'JAMES BEARD', year: 2018, result: 'Nominee', category: 'Food TV' } ],
    watch_providers: { US: { flatrate: ['Max', 'Discovery+', 'Hulu'], rent: ['Prime Video'], buy: ['Apple TV'] } },
    ratings_trend: [0.82, 0.78, 0.76, 0.78, 0.74, 0.76, 0.76, 0.72],
    social_velocity: 48,
    certification: 'TV-G',
  },
  13: {
    tmdb_id: 333339, media_type: 'movie',
    title: 'READY PLAYER ONE', original_title: 'Ready Player One',
    tagline: 'A better reality awaits.',
    overview: "When the creator of the OASIS — a virtual-reality universe where billions come to work, play, and escape — passes away, he leaves behind a single challenge: the keys to his kingdom hidden inside the game itself. Teenager Wade Watts joins a global hunt that will pull him from his grim suburban 'Stacks' into a realm of pop-culture artifacts, corporate villains, and impossible physics.",
    release_date: '2018-03-29', first_air_date: null,
    runtime: 140, status: 'Released',
    genres: ['Adventure', 'Science Fiction', 'Action'],
    keywords: ['video game', 'based on novel or book', 'future', 'virtual reality', 'dystopia', 'nostalgia', 'love', 'evil corporation', 'energy', 'challenge', 'map', 'egg hunt', 'based on young adult novel', 'columbus ohio'],
    vote_average: 7.6, vote_count: 11204, popularity: 284.7,
    production_companies: [
      { name: 'Amblin Entertainment', logo_path: null },
      { name: 'Warner Bros. Pictures', logo_path: null },
      { name: 'Village Roadshow Pictures', logo_path: null },
    ],
    networks: [{ name: 'HBO', logo_path: null }],
    created_by: [{ name: 'Steven Spielberg', job: 'Director' }],
    credits: {
      cast: [
        { name: 'Tye Sheridan',    character: 'Wade Watts / Parzival',         order: 0 },
        { name: 'Olivia Cooke',    character: 'Samantha Cook / Art3mis',       order: 1 },
        { name: 'Ben Mendelsohn',  character: 'Nolan Sorrento',                order: 2 },
        { name: 'Mark Rylance',    character: 'James Halliday / Anorak',       order: 3 },
        { name: 'Lena Waithe',     character: 'Helen Harris / Aech',           order: 4 },
        { name: 'T.J. Miller',     character: 'i-R0k',                         order: 5 },
        { name: 'Simon Pegg',      character: 'Ogden Morrow',                  order: 6 },
      ],
      crew: [
        { name: 'Steven Spielberg', job: 'Director' },
        { name: 'Zak Penn',         job: 'Screenplay' },
        { name: 'Ernest Cline',     job: 'Screenplay (Novel)' },
        { name: 'Janusz Kamiński',  job: 'Director of Photography' },
        { name: 'Alan Silvestri',   job: 'Original Music' },
      ]
    },
    budget: 175_000_000, revenue: 582_890_172,
    deal_value: 84_200_000, rights_cost: 14_500_000,
    awards: [
      { label: 'OSCAR',   year: 2019, result: 'Nominee', category: 'Best Visual Effects' },
      { label: 'SATURN',  year: 2019, result: 'Winner',  category: 'Best Science Fiction Film' },
      { label: 'HUGO',    year: 2019, result: 'Nominee', category: 'Best Dramatic Presentation' },
      { label: 'BAFTA',   year: 2019, result: 'Nominee', category: 'Best Special Visual Effects' },
    ],
    watch_providers: { US: { flatrate: ['Max'], rent: ['Apple TV', 'Prime Video', 'YouTube'], buy: ['Apple TV', 'Prime Video', 'Vudu'] } },
    ratings_trend: [1.42, 1.58, 1.74, 1.81, 1.92, 1.98, 2.02, 2.06],
    social_velocity: 268,
    certification: 'PG-13',
    backdrop_url: 'assets/rpo-backdrop.jpg',
    poster_url:   'https://image.tmdb.org/t/p/w500/pU1ULUq8D3iRxl1fdX2lZIzdHuI.jpg',
    trailer: { key: 'cSp1dM2Vj48', site: 'YouTube', url: 'https://www.youtube.com/watch?v=cSp1dM2Vj48' },
  },
};

// Helpers
function getTMDB(rank) { return TMDB_RECORDS[rank] || null; }
function getGenreBackdrop(genre) {
  const key = genre || 'Drama';
  return GENRE_BACKDROPS[key] || GENRE_BACKDROPS['Drama'];
}

window.SASMASTER_TMDB = { TMDB_RECORDS, GENRE_BACKDROPS, getTMDB, getGenreBackdrop };
